#!/usr/bin/env bash

PROJECT_NAME=HubicGTK
PROJECT_VERSION=${PROJECT_VERSION:-"dev"}
PROJECT_CONTACT_MAIL=bugs@depar.is
DOMAIN_NAME=hubic-gtk
PO_ROOT=${PO_ROOT:-"./po"}

if [ "$1" = "init" ]; then
    if [ ! -d "${PO_ROOT}" ]; then
        mkdir "${PO_ROOT}"
    fi
    if [ -f "${PO_ROOT}/${DOMAIN_NAME}.pot" ]; then
        rm "${PO_ROOT}/${DOMAIN_NAME}.pot"
    fi

    xgettext --language=Python --keyword=_ --keyword=N_ \
        --copyright-holder="$PROJECT_NAME volunteers" \
        --package-name=$PROJECT_NAME --package-version=$PROJECT_VERSION \
        --msgid-bugs-address=$PROJECT_CONTACT_MAIL \
        --output=${DOMAIN_NAME}.pot ${DOMAIN_NAME}.py

    sed -i "s|SOME DESCRIPTIVE TITLE.|$PROJECT_NAME Translation Effort|" ${DOMAIN_NAME}.pot
    sed -i "s|Content-Type: text/plain; charset=CHARSET|Content-Type: text/plain; charset=UTF-8|" ${DOMAIN_NAME}.pot
    mv ${DOMAIN_NAME}.pot "${PO_ROOT}/"

elif [ "$1" = "create" ]; then
    mkdir -p "${PO_ROOT}/$2/LC_MESSAGES/"
    msginit -l $2 -i "${PO_ROOT}/${DOMAIN_NAME}.pot" -o "${PO_ROOT}/$2/LC_MESSAGES/$DOMAIN_NAME.po"

elif [ "$1" = "compile" ]; then
    msgfmt -o "${PO_ROOT}/$2/LC_MESSAGES/$DOMAIN_NAME.mo" "${PO_ROOT}/$2/LC_MESSAGES/$DOMAIN_NAME.po"

elif [ "$1" = "update" ]; then
    # commande à base de msgmerge pour mettre à jour une langue.
    cp "${PO_ROOT}/$2/LC_MESSAGES/$DOMAIN_NAME.po" "${PO_ROOT}/$2/LC_MESSAGES/$DOMAIN_NAME.old.po"
    msgmerge --lang $2 -o "${PO_ROOT}/$2/LC_MESSAGES/$DOMAIN_NAME.po" "${PO_ROOT}/$2/LC_MESSAGES/$DOMAIN_NAME.old.po" ${PO_ROOT}/${DOMAIN_NAME}.pot
fi
